# Site settings
title: Youbionic
email: youbionic@gmail.com
description: >
  We work to create devices that support or replace parts of the body in order to make our lives better  
lang: en-US

baseurl: "/Youbionic" # the subpath of your site, e.g. /blog/
url: https://youbionic-com.github.io/Youbionic/ # the base hostname & protocol for your site
git_address: https://github.com/Youbionic-com/Youbionic
git_edit_address: https://github.com/Youbionic-com/Youbionic/master
website: https://www.youbionic.com


# on all pages (and the first three you list display with greeting, if included)
social:
  facebook-official: https://facebook.com/Youbionic-1447353702171072/
  youtube: http://www.youtube.com/channel/UCkk_Sxe8MZ64RcNQbXw_MjQ
  twitter: https://twitter.com/youbionic
  github: https://github.com/Youbionic
  linkedin-square: https://www.linkedin.com/in/federicociccarese
  instagram: http://instagram.com/youbionic
  google-plus-square: https://plus.google.com/u/0/+HaliFlame  

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
